#!/bin/sh

#
# Perform backup to Tauro 1TB External drive.
# Should be done weekly.
#


read -p "Shall we mount /mnt/backup [y]?" yn
case $yn in
    [NnQq]* ) exit;;
    * ) mount /mnt/backup;;
esac



read -p "Shall we run rdiff-backup [y]?" yn
case $yn in
    [NnQq]* ) exit;;
    * ) rdiff-backup --print-statistics \
	--exclude /home/ziarkaen/nobackup \
	--exclude /home/ziarkaen/torrents \
	/home/ziarkaen /mnt/backup/home;;
esac



read -p "Shall we unmount /mnt/backup [y]?" yn
case $yn in
    [NnQq]* ) exit;;
    * ) umount /mnt/backup;;
esac


echo "Backup completed."
