#!/bin/bash

# Search Google via dmenu

CACHE_FILE=$HOME/.cache/dsearch/history

test -d "$d" || mkdir -p `dirname $CACHE_FILE`

if [ -f $HOME/.dmenurc ]; then
  . $HOME/.dmenurc
else
  DMENU='dmenu -i'
fi

GS=`cat $CACHE_FILE | $DMENU $*`

if grep -q "$GS" "$CACHE_FILE" ; then
    echo "already exists in history"
else
    echo $GS >> $CACHE_FILE
fi

chromium http://www.google.co.uk/search?q="$GS"

